### ISSUE TITLE
看着有点眼熟

### ISSUE THREAD

**Issue by zippo88888888** [ljphawk/SwipeMenuLayout#3]
https://github.com/jdsjlzx/LRecyclerView/blob/master/app/src/main/java/com/lzx/demo/view/SwipeMenuView.java

**Comment by ljphawk** [comment]
哈哈 其实是这样 写这个之前 看过其他库支持的功能和大致判断逻辑，你仔细看，功能是有所增加的，逻辑和判断也不一样
